version: '3.8'
services:
    java-maven-app:
      image: denchikkarate/demo-app:jma-aws
      ports:
        - 8085:8080
    postgres:
      image: postgres:13
      ports:
        - 5433:5432
      environment:
        - POSTGRES_PASSWORD=my-pwd
